name: Build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install & build
        run: make
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Publish to npm
        run: make publish
        if: github.event_name == 'release'
